### PR TITLE
Some fixes and enhancements

### PR DESCRIPTION
**Pull request by Liborsaf**

### CODE REVIEW

**Comment by pkejval** [comment]
Thank you very much for contributing! I just fixed your TABS to spaces (I don't wanna fight which is better, VSCode just defaults to spaces :)) ) and simplified some conditions to oneliners.

**Comment by pkejval** [comment]
I found issue with

```
while IFS= read -r URL
do
    run_uld $URL
done < /downloads/download.txt
```

If line in `/downloads/download.txt` is not ended with newline, this code won't read it.

Example:
```
http://adress1
http://adress2
https://fsdfsdfsdfsdf
```
Last line `https://fsdfsdfsdfsdf`` will be omitted because user didn't click ENTER after pasting it.

```
http://adress1
http://adress2
https://fsdfsdfsdfsdf

```

`https://fsdfsdfsdfsdf`` will be included because there is newline after it.

Do you know solution to this problem? I reverted code to use cat again for now.

**Comment by Liborsaf** [comment]
I have pushed changes on it to my fork, maybe this will work (but honestly don't know if it is better then just using cat, but it stops shellcheck from complaining, so...). Can you try this and let me know?

Btw can you please add editorconfig to this repo? It would help to maintain those spaces and tabs thing. :)

Also sorry for my english :D

**Comment by pkejval** [comment]
Můžeme klidně česky. :)

Všechny způsoby čtení testuji skriptem dole. 

Změnil jsem to na `for URL in $(< /downloads/download.txt)` funguje dobře a ShellCheck je s ním spokojen... :)

```
#!/bin/bash

DEFAULT_PARTS=${PARTS:-20}

for URL in $(cat test.txt)
do
	PARTS=$DEFAULT_PARTS
	LINE=$(echo "$URL" | cut -d ";" -f 1)
	[[ "$LINE" == PARTS=* ]] && eval "$LINE" && echo -n "Set $LINE for " && URL=$(echo "$URL" | cut -d ";" -f 2) && echo "$URL"

	echo "Downloading $URL with $PARTS"
done

echo ""
echo "-----"
echo ""

for URL in $(<test.txt)
do
	PARTS=$DEFAULT_PARTS
	LINE=$(echo "$URL" | cut -d ";" -f 1)
	[[ "$LINE" == PARTS=* ]] && eval "$LINE" && echo -n "Set $LINE for " && URL=$(echo "$URL" | cut -d ";" -f 2) && echo "$URL"

	echo "Downloading $URL with $PARTS"
done

echo ""
echo "-----"
echo ""

while IFS=$'\012' read -r URL
do
	PARTS=$DEFAULT_PARTS
	LINE=$(echo "$URL" | cut -d ";" -f 1)
	[[ "$LINE" == PARTS=* ]] && eval "$LINE" && echo -n "Set $LINE for " && URL=$(echo "$URL" | cut -d ";" -f 2) && echo "$URL"

	echo "Downloading $URL with $PARTS"
done < test.txt

echo ""
echo "-----"
echo ""

while IFS= read -r URL
do
	PARTS=$DEFAULT_PARTS
	LINE=$(echo "$URL" | cut -d ";" -f 1)
	[[ "$LINE" == PARTS=* ]] && eval "$LINE" && echo -n "Set $LINE for " && URL=$(echo "$URL" | cut -d ";" -f 2) && echo "$URL"
	echo "Downloading $URL with $PARTS"
done < <(grep . test.txt)
```

**Pull request merged**
